CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_is_active_idx" ON "users" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "instructor_profiles_user_id_idx" ON "instructor_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "instructor_profiles_approval_status_idx" ON "instructor_profiles" USING btree ("approval_status");--> statement-breakpoint
CREATE INDEX "student_profiles_user_id_idx" ON "student_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "admin_profiles_user_id_idx" ON "admin_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "courses_instructor_id_idx" ON "courses" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "courses_is_published_idx" ON "courses" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "courses_deleted_at_idx" ON "courses" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "courses_domain_idx" ON "courses" USING btree ("domain");--> statement-breakpoint
CREATE INDEX "sections_course_id_idx" ON "sections" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "lectures_section_id_idx" ON "lectures" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX "lectures_mux_asset_id_idx" ON "lectures" USING btree ("mux_asset_id");--> statement-breakpoint
CREATE INDEX "lectures_is_published_idx" ON "lectures" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "live_classes_lecture_id_idx" ON "live_classes" USING btree ("lecture_id");--> statement-breakpoint
CREATE INDEX "live_classes_instructor_id_idx" ON "live_classes" USING btree ("instructor_id");--> statement-breakpoint
CREATE INDEX "live_classes_status_idx" ON "live_classes" USING btree ("status");--> statement-breakpoint
CREATE INDEX "live_classes_status_scheduled_at_idx" ON "live_classes" USING btree ("status","scheduled_at");--> statement-breakpoint
CREATE INDEX "live_classes_recording_status_idx" ON "live_classes" USING btree ("recording_status");--> statement-breakpoint
CREATE INDEX "enrollments_student_id_idx" ON "enrollments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "enrollments_course_id_idx" ON "enrollments" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "progress_student_id_idx" ON "progress" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "progress_lecture_id_idx" ON "progress" USING btree ("lecture_id");--> statement-breakpoint
CREATE INDEX "assignments_lecture_id_idx" ON "assignments" USING btree ("lecture_id");--> statement-breakpoint
CREATE INDEX "submissions_assignment_id_idx" ON "submissions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "submissions_student_id_idx" ON "submissions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "quiz_questions_assignment_id_idx" ON "quiz_questions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "certificates_student_id_idx" ON "certificates" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "certificates_course_id_idx" ON "certificates" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "payments_student_id_idx" ON "payments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "payments_course_id_idx" ON "payments" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "payments_status_idx" ON "payments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "channels_course_id_idx" ON "channels" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "messages_channel_id_idx" ON "messages" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "messages_channel_created_at_idx" ON "messages" USING btree ("channel_id","created_at");--> statement-breakpoint
CREATE INDEX "messages_sender_id_idx" ON "messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notifications_user_is_read_idx" ON "notifications" USING btree ("user_id","is_read");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_id_idx" ON "audit_logs" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "audit_logs_entity_idx" ON "audit_logs" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_logs_action_idx" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "password_resets_token_hash_idx" ON "password_resets" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "password_resets_user_id_idx" ON "password_resets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "email_verifications_token_hash_idx" ON "email_verifications" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "email_verifications_user_id_idx" ON "email_verifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_auth_providers_user_id_idx" ON "user_auth_providers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "refresh_tokens_family_idx" ON "refresh_tokens" USING btree ("family");--> statement-breakpoint
CREATE INDEX "beta_invites_invited_by_idx" ON "beta_invites" USING btree ("invited_by");--> statement-breakpoint
CREATE INDEX "beta_invites_email_idx" ON "beta_invites" USING btree ("email");--> statement-breakpoint
CREATE INDEX "reviews_course_id_idx" ON "reviews" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "reviews_user_id_idx" ON "reviews" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "reviews_course_moderation_idx" ON "reviews" USING btree ("course_id","moderation_status");--> statement-breakpoint
CREATE INDEX "jobs_posted_by_idx" ON "jobs" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "jobs_course_id_idx" ON "jobs" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "jobs_domain_idx" ON "jobs" USING btree ("domain");--> statement-breakpoint
CREATE INDEX "jobs_is_active_idx" ON "jobs" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "institution_accounts_contact_email_idx" ON "institution_accounts" USING btree ("contact_email");--> statement-breakpoint
CREATE INDEX "institution_enrollments_account_id_idx" ON "institution_enrollments" USING btree ("institution_account_id");--> statement-breakpoint
CREATE INDEX "institution_enrollments_student_id_idx" ON "institution_enrollments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "institution_enrollments_course_id_idx" ON "institution_enrollments" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "uploads_lecture_id_idx" ON "uploads" USING btree ("lecture_id");--> statement-breakpoint
CREATE INDEX "uploads_user_id_idx" ON "uploads" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "uploads_status_idx" ON "uploads" USING btree ("status");