export { DashboardShell } from './DashboardShell'
export { AppSidebar } from './AppSidebar'
export { DashboardSiteHeader } from './DashboardSiteHeader'
export { NavSection } from './NavSection'
export { UserMenu } from './UserSection'
export { MetricCard, MetricCardGrid } from './MetricCard'
export { ActivityList } from './ActivityList'
export { QuickActions } from './QuickActions'
export { StatusBadge } from './StatusBadge'
export { StudentDashboard } from './StudentDashboard'
export type { DashboardShellProps } from './DashboardShell'
export type { NavItem, NavGroup, FooterLink } from './NavSection'
export type { ActivityItem } from './ActivityList'
export type { QuickAction } from './QuickActions'
export type { StatusVariant } from './StatusBadge'