export { DashboardShell } from './DashboardShell'
export { DashboardSidebar } from './DashboardSidebar'
export { DashboardHeader } from './DashboardHeader'
export { MobileSidebar } from './MobileSidebar'
export { NavSection } from './NavSection'
export { UserMenu } from './UserSection'
export { MetricCard, MetricCardGrid } from './MetricCard'
export { ActivityList } from './ActivityList'
export { QuickActions } from './QuickActions'
export { StatusBadge } from './StatusBadge'
export { StudentDashboard } from './StudentDashboard'
export type { DashboardShellProps, NavItem } from './DashboardShell'
export type { ActivityItem } from './ActivityList'
export type { QuickAction } from './QuickActions'
export type { StatusVariant } from './StatusBadge'