// Export all schema tables
export * from './enums';
export type { AccessType } from './enums';
export { UserRole } from './enums';
export const CourseStatusValues = ['draft', 'in_review', 'revision_requested', 'published', 'archived'] as const;
export const CourseStructureValues = ['live', 'normal'] as const;
export type CourseStatusType = typeof CourseStatusValues[number];
export type CourseStructureType = typeof CourseStructureValues[number];
export * from './users';
export * from './admin-profiles';
export * from './student-profiles';
export * from './instructor-profiles';
export * from './institution-accounts';
export * from './institution-enrollments';
export * from './beta-invites';
export * from './courses';
export * from './live-classes';
export * from './recurring-schedules';
export * from './sections';
export * from './lectures';
export * from './lesson-attachments';
export * from './enrollments';
export * from './assignments';
export * from './payments';
export * from './certificates';
export * from './progress';
export * from './email-verifications';
export * from './password-resets';
export * from './refresh-tokens';
export * from './user-auth-providers';
export * from './notifications';
export * from './user-notification-preferences';
export * from './messages';
export * from './channels';
export * from './channel-members';
export * from './jobs';
export * from './quiz-questions';
export * from './audit-logs';
export * from './platform-settings';
export * from './waitlist';
export * from './reviews';
export * from './uploads';
export * from './submissions';
